name: flutter_elastic_list_view
description: "Elastic ListView for Flutter"
repository: https://github.com/monster555/flutter_elastic_list_view
version: 0.0.1
homepage: https://github.com/monster555/flutter_elastic_list_view

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  dart_code_metrics: ^5.7.3
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

